### ISSUE TITLE
Umstrukturierung auf CMS-Basis

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#10]
Der Plugin-Code soll gemäß den Vorgaben der CMS-Basis umgestellt werden:
https://gitlab.rrze.fau.de/rrze-webteam/cms-basis/tree/master

Insbesondere:
* Verschiebung der Dateien in neue Ordner, falls notwendig
* Entrümpelung der Basisdatei
* OOP

**Comment by thenickless** [comment]
in 4.3.6 umgesetzt
