### ISSUE TITLE
Filterung der Ansicht der Beiträge im Backend auf eigene Quelle

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#102]
Wenn ich auf meiner eigenen Site FAQs habe und hier eigene suchen will, wird bei einer vorgenommenen Syncronisierung die Suche & Ansicht etwas erschwert.
(Betrifft Ansicht aller FAQs und der Kategorien und Schlagwörter).

Es wäre schön, wenn man hier eine Option bekäme, dass man nur die Einträge aus der lokalen SIte (Quelle website) bekommt.

**Comment by thenickless** [comment]
es gibt jetzt ein Dropdown zum Filtern mit allen Quellen
