### ISSUE TITLE
Neue Auswahl von Remote Domains

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#11]
Bei der Registrierung von Remote Domains soll das Protokoll gesondert angegeben werden können und der Typ der jeweiligen API. Wenn die jeweilige API es verlangt, soll auch ein APIKey/UserKey hinterlegt werden können mit dem die Abfrage gemacht wird.

D.h. folgende Abfragen:
* Domain
* Protokoll 
    * (http oder https, wobei SSL per default eingeschaltet ist)
* API-Typ 
    * WordPress
    * OTRS (siehe #5 )
    * ...andere

**Comment by thenickless** [comment]
in 4.3.6 enthalten
