### ISSUE TITLE
GET request für Filterung nach Kriterien (Beispiel: nach faq_category und faq_tag)

### ISSUE THREAD

**Issue by anfalas** [RRZE-Webteam/rrze-faq#115]
Um eine Liste von FAQs darzustellen und Beiträge selektierbar in anderen Applikationen darstellen zu können ist eine Filterung notwendig (Nutzer:in möchte nur FAQs angezeigt bekommen die Kriterien XY entsprechen). das resultierende JSON kann dann weiter interpretiert werden.

**Comment by thenickless** [comment]
Beispiel:
https://www.anleitungen.rrze.fau.de/wp-json/wp/v2/faq

Filterungen:

Tag:
https://www.anleitungen.rrze.fau.de/wp-json/wp/v2/faq?filter[faq_tag]=Matrix

Mehrere Tags:
https://www.anleitungen.rrze.fau.de/wp-json/wp/v2/faq?filter[faq_tag]=Matrix%2BAccounts

Kategorie:
https://www.anleitungen.rrze.fau.de/wp-json/wp/v2/faq?filter[faq_category]=Dienste

Tags und Kategorien:
https://www.anleitungen.rrze.fau.de/wp-json/wp/v2/faq?filter[faq_category]=Dienste&filter[faq_tag]=Sprache
