### ISSUE TITLE
Optionale Angabe eines Ankertextes für die Nutzung der FAQs in der Ausgabe als Accordion

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#116]
Aktuell werden die Anker der Accordions anhand der ID gebaut.

Dadurch sieht der Link z.B. so aus:
https://www.anleitungen.rrze.fau.de/serverdienste/matrix-an-der-fau/matrix-faq/**#ID-11504**

Es gibt den Wunsch, hier manuell einen leichter merkbaren, "sprechenden Namen" angeben zu können, so daß der LInk z.B. so aussehen könnte:
https://www.anleitungen.rrze.fau.de/serverdienste/matrix-an-der-fau/matrix-faq/**#entschluesseln**

Ich könnte mir vorstellen, dass man hierzu die Eingabe einer FAQ um eine Custom Field für einen Text (zu sanitizen als Slug, also nur `[a-z0-9\-_]+` ) ergänzt.
Und bei der Ausgabe dann, wenn dieses optionale Feld befüllt ist, es dann anstelle der ID bei dem Shortcode des Accordions übergibt.

Ob es Dupletten oder Mehrfachnutzung gibt, wäre mir an der Stelle egal, würde ich sogar bewusst zulassen und auch keine Prüfung nach machen. Der User muss halt wissen was er tut, und es kann durchau sein, dass FAQs unterschiedlicher Kategorien durchaus mal den selben Sprungmarker nutzen wollen, wenn Sie die FAQs auf unterschiedlichen Seiten ausgeben.
Der Sprunganker kann nur an der Quelle der FQQ eingegeben werden. Sites, die die FAQ. nur syncen können sie ebensowenig ändern wie die anderen Felder.

**Comment by thenickless** [comment]
Es muss geprüft werden, dass das auch bei Gruppierungen (= äußere und innere Akkordeons) mit rrze-elements funktioniert. Vgl https://github.com/RRZE-Webteam/rrze-faq#erkl%C3%A4rungen-und-werte-zu-den-attributen-des-shortcodes

zB #innerID-3585

**Comment by thenickless** [comment]
Umgesetzt.

Tests:
- [ ] ohne Attribute
- [ ] explizite IDs
- [ ] glossary
- [ ] categories
- [ ] eigene FAQ
- [ ] gesyncte FAQ

(Zu sanitizen: WP empfiehlt sanitize_title() statt eigener RegEx zu verwenden.)
