### ISSUE TITLE
FAQ-Widget

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#14]
Es soll ein Widget bereit gestellt werden mit dessen Hilfe einzelne FAQ-EInträge in die Sidebar eingeblendet werden können.
Dabei entweder 
* fest ausgewählte einzelne 
* ein Eintrag aus einer gewählten Kategorie, wobei der einzelne Eintrag via Random gewählt wird
* ein fest definierter EIntrag aber nur binnen einer angegebenen Zeit von / bis Datum.

**Comment by thenickless** [comment]
Ist dieses Issue noch aktuell?

**Comment by xwolfde** [comment]
Jupp. Eine Widget-Funktion für die Anzeige von FAQs unter Widgets wäre schön.
