### ISSUE TITLE
Angabe der Sprache in der API

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#16]
Die API zeigt derzeit nicht an, in welcher Sprache der Content übermittelt wird.
vgl. $DOMAIN/wp-json/wp/v2/glossary 

Wenn man den Content ion einer Website importiert, die eine andere Sitesprache hat, kommt es jedoch zu Problemen der Zugänglichkeit.
Daher sollte 
1. Die Ausgabe der API um die Sprache bei den jeweiligen Inhaltsteilen ergänzt werden (ggf. als Attribut lang="") .
2. Bei der Ausgabe der FAQs sollen dann die Sprachangaben um den Text herum angegeben werden, wenn sich die Sprache des Inhalts von der Site-Sprache unterscheidet.

**Comment by thenickless** [comment]
in 4.3.6 enthalten
