### ISSUE TITLE
Weitere FAQ-Quellen identifizieren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#18]
Prüfen, ob es noch weitere FAQ-Quellen im FAU-Umfeld gibt, welche über REST-APIs oder andere nutzbare APIs verfügen.

**Comment by thenickless** [comment]
Ist dieses Issue noch aktuell?

In 4.3.6 können alle Domains, die das Plugin RRZE-FAQ im Einsatz haben, registriert und deren FAQ, Kategorien und Schlagwörter synchronisiert werden.

**Comment by xwolfde** [comment]
Ist im Prinzip eine Daueraufgabe von aber geringer Prio.

Es geht darum, ob es noch andere Webanwendungen gibt, die eine FAQ mitbringen (z.B. gitlab?) und ob man von diesen syncen könnte.
Aber ich denke, wir können das als Issue erstmal dicht machen und reagieren auf konkrete Bedarfsanfragen.
