### ISSUE TITLE
Schema Markup FAQ ergänzen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#20]
Wenn das Markup für die Strukturierung nach FAQ gegeben wird, kann Google dies auswerten.
Das bietet einige Vorteile. Würde aber dann ausdrücklich die Fragen/Titel als FAQ vorsehen.
Daher würde es Sinn machen, das Markup dann zu setzen, wenn man einen entsprechenden Schalter global oder pro Eintrag gesetzt hat.

**Comment by thenickless** [comment]
In 4.7.0 umgesetzt.
Info: Schema wird nur für FAQ ausgegeben, die auf der Website eingegeben wurden - nicht für synchronisierte. Grund: Google mag Duplicate Content nicht.
