### ISSUE TITLE
Gezielte und sortierte Angabe von FAQs über Ids

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#28]
Wenn man mehrere Id-Nummern im Shortcode eingibt, werden die angegebenen FAQs in der Reihenfolge der Nummern angezeigt.

Beispiel:
[faq id="100, 10, 300"]

Dann erfolgt  die Ausgabe auch in der Reihenfolge der angegebenen Ids und nicht in alphabetischer Reihenfolge der Titel.

**Comment by thenickless** [comment]
ist in 4.12.0 umgesetzt

**Comment by thenickless** [comment]
Closed, da für Classic Editor umgesetzt. Issue für Gutenberg unter https://github.com/RRZE-Webteam/rrze-faq/issues/57#issue-609902288
