### ISSUE TITLE
Metabox mit hilfreicher SHortcode-Anzeige reaktivieren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#29]
Bitte im Editor (Default Editor) wieder eine Metabox ergänzen, in dem die Shortcodes für den jeweiligen FAQ-EIntrag  zum leichten kopieren angezeigt werden.

Mindestens die Anzeige der [faq id="$nummer"] und dynamisch (weil on click änderbar), wenn die Kategorie definiert wurde auch in der Form [faq category="$kategorie"] .

**Comment by xwolfde** [comment]
Bei Nutzung von Gutenberg: Kann man bei Gutenberg dies als Hilfe-Box irgendwo anzeigen?

**Comment by thenickless** [comment]
Ist in 4.4.0 (aktuell noch auf dev - wird in Kürze mit master gemerged) umgesetzt. 
Sowohl beim Classic Editor als auch bei Gutenberg werden die Infos unterhalb des FAQ ausgeben.
