### ISSUE TITLE
Verlinkung von Einträgen mit Personen wenn FAU Kontakte aktiv

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#3]
Verschoben aus https://github.com/RRZE-Webteam/FAU-Einrichtungen/issues/207#issuecomment-273185466

"Nach kurzem Telefonat ergänze ich die Beschreibung des Wunsches um den konkreten Anwendungsfall:
Es soll ein Schlagwortverzeichnis angelegt werden mit den wichtigsten Begriffen für Erstsemester, die sich noch nicht so gut auskennen. Hier soll beispielsweise statt eines allgemeinen Links auf die Studienberatung konkret auf die zuständige Person verlinkt werden. Dazu wäre es natürlich sinnig, die Kontaktinformationen auch im Glossar zur Verfügung zu haben (zur Verdeutlichung, was gemeint ist, gibt es hier einen screenshot:)
![bildschirmfoto 2017-01-17 um 15 04 48](https://cloud.githubusercontent.com/assets/11296947/22024698/1af60900-dccb-11e6-83eb-c1d4117d8e8f.png)
Nachdem momentan nicht viel Zeit ist, die Idee an sich aber meiner Ansicht nach sinnvoll, gibt es jetzt das Label "enhancement". 
"

**Comment by xwolfde** [comment]
Konkretisierung:
Wenn das Plugin FAU Person aktiv ist, dann soll es ermöglicht werden, mit einem weiteren Custom Field eine Verknüpfung mit der Id einer Person anzugeben.

Diese soll dann später bei der Ausgabe der FAQ via Shortcode mit einem Parameter berücksichtigt werden können, so daß man alle FAQs zu einer Person ausgeben kann.

Z.B. könnte jeder Kontakt zu sich somit eigene Sprechzeiten oder andere Notizen in der FAQ abgelegt haben.

**Comment by thenickless** [comment]
Ist dieses Issue noch aktuell?

**Comment by xwolfde** [comment]
Ich denke nicht, dass es wirklich notwendig ist, da man die FAQs ja als Shortcode verwendet und daher selbst eine Verknüpfung der Seite mit einer Person machen kann.
