### ISSUE TITLE
Persistente Sprungmarken

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-faq#30]
Problem: 
Der anchor ändert sich, wenn FAQ hinzu kommen oder gelöscht werden. Dadurch kann nicht auf FAQ derart verlinkt werden, dass die Seite mit entsprechendem geöffnetem Akkordeon geladen wird. 

Beispiel:
https://www.anleitungen.rrze.fau.de/multimedia/zoom/#collapse_3

Lösung:
#FAQID
#category_slug
#tag_slug

Beispiel:
https://www.anleitungen.rrze.fau.de/multimedia/zoom/#12345
https://www.anleitungen.rrze.fau.de/multimedia/zoom/#anleitungen
https://www.anleitungen.rrze.fau.de/multimedia/zoom/#zoom

**Comment by thenickless** [comment]
War bereits in RRZE-FAQ integriert, funktioniert jedoch nicht wg RRZE-Elements - siehe https://github.com/RRZE-Webteam/rrze-elements/issues/88

**Comment by cassandre** [comment]
Erledigt in https://github.com/RRZE-Webteam/rrze-elements/commit/2ab6feb3f10fe48458dfcdd731f3296c0ac0871d. Kann geschlossen werden?

**Comment by thenickless** [comment]
Kann noch nicht geschlossen werden - siehe https://github.com/RRZE-Webteam/rrze-elements/issues/88#issuecomment-617015054

**Comment by thenickless** [comment]
in 4.9.10 umgesetzt
