### ISSUE TITLE
Vereinfachung der Attribute für den Shortcode

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-faq#31]
Siehe Dev-Branch von FAU-Person

**Comment by xwolfde** [comment]
Konkret:

* format=""  -> definiert die Defaultausgabe
* show="parameter1, Parameter2" -> ergänzt die Defaultausgabe
* hide="parameter1, parameter2" - entfernt Elemente von der Defaultausgabe
* class="" - Für eine etwaige CSS-Klasse für das umrandende div.
* sort="" - (default ist title), hier ggf. auch vorsehen: "id", dann Sortierung nach Id-Nummer
* order="" (default asc), hier ggf. desc auch ermöglichen


Beispiele (Parameternamen jetzt nur aus dem Stehgreif als Beispiel. Könntena uch anders lauten):

* [faq format="faq"]  enstpricht, weil es default ist [faq]. Keine Änderung der Ausgabe
* [faq hide="title"] würde aus der Ausgabe den titel entfernen
* [faq hide="accordion"]  würde das Accordion entfernen
* [faq hide="az-navi"]  würde das A-Z oberhalb entfernen

**Comment by xwolfde** [comment]
Apropros Sort: Kann man dazu die WP-Funktion verwenden?
![grafik](https://user-images.githubusercontent.com/1070669/79218136-7b9abf80-7e3f-11ea-83b0-ed41cb4a6be1.png)

**Comment by thenickless** [comment]
Mir ist nicht klar, wie die Attribute für den Shortcode vereinfacht werden sollen. Bitte um Feedback.


Aktuell gibt es folgende Attribute, die allesamt optional sind:


[faq 
glossary="category oder tag" 
category="beliebig-viele-kategorien-kommagetrennt"  
tag="beliebig-viele-schlagwoerter-kommagetrennt" 
glossarystyle="a-z oder tagcloud oder tabs" 
color="medfak oder natfak oder rwfak oder philfak oder techfak" 
id="123456"
hideaccordeon="1"] 



Die Attribute haben folgende Auswirkungen:


glossary : bestimmt, wonach gruppiert werden soll. Mögliche Werte sind "category" oder "tag". D.h. entweder es wird nach den Kategorien gruppiert oder nach Schlagwörtern. Um gar nicht zu gruppieren, reicht es, das Attribut glossary wegzulassen.


category : mit diesem Attribut wird bestimmt, zu welchen Kategorien passende FAQ ausgegeben werden sollen. Es können beliebig viele Kategorien angegeben werden. Nutzen Sie dazu die Titelform der Kategorien, die Sie im Menü unter "FAQ"->"Kategorie" finden und trennen Sie diese voneinander durch Kommata.


tag : mit diesem Attribut wird bestimmt, zu welchen Schlagwörtern passende FAQ ausgegeben werden sollen. Es können beliebig viele Schlagwörter angegeben werden. Nutzen Sie dazu die Titelform der Schlagwörter, die Sie im Menü unter "FAQ"->"Schlagwörter" finden und trennen Sie diese voneinander durch Kommata.


glossarystyle : dieses Attribut bestimmt, wie das Glossar oberhalb der FAQ aussehen soll. 
Mögliche Werte sind 
 - "a-z" für ein alphabetisches Register von A bis Z
 - "tagcloud" um die Begriffe, nach denen gruppiert wird anhand der Anzahl an gefundenen Treffer unterschiedlich groß darzustellen. Gruppiert wird nach Kategorien oder nach Schlagwörtern. Siehe "glossary". 
 - "tabs" um die Begriffe, nach denen gruppiert wird, im Glosar darzustellen.
Aus Gründen der Abwärtskompatibilität ist es nötig, dass Sie glossarystyle="" verwenden müssen, wenn Sie kein Glossar anzeigen lassen möchten.


color : bestimmt, in welcher Farbe die Accordeons erscheinen sollen. Verweden Sie dazu die Kennungen der Fakultäten: medfak oder natfak oder rwfak oder philfak oder techfak


id : mit diesem Attribut erfolgt die Ausgabe eines oder mehrerer FAQ. Sie finden die ID in der rechten Spalte unter "FAQ"->"Alle FAQ" sowie in der Informationsbox "Einfügen in Seiten und Beiträgen" bei jedem FAQ im Bearbeitungsmodus. Sie können damit auch die Reihenfolge der FAQ in der Ausgabe bestimmen. 


hideaccordeon : ist das Attribut "id" gesetzt, können Sie mit hideaccordeon bestimmen, dass die Ausgabe nicht in einem Accordeon erfolgen soll.

**Comment by thenickless** [comment]
Nachdem ich mir alle Attribute von Accordeon und die Mails von D.d.W. angesehen habe, schlage ich folgende Vereinfachung vor:

Aktuell gibt es 7 Attribute, nach Umsetzung dieser Idee dann 4. Kein Attribut ist verpflichtend.

[faq layout="..." category="..." tag="..." id="..."]

Mit dem Attribut "layout können alle Formen samt Farbe des Accordeons und ob und worauf bezogen das Glossar in welcher Art angezeigt werden soll.

Mögliche Werte für "layout":

- no_accordeon
- no_title
- no_glossary
- expand_button (Expand all button vom Accordeon wird angezeigt)
- expanded ( alle Accordeons werden geöffnet geladen)

- medfak
- natfak
- philfak
- rwfak
- techfak

- a-z
- tabs
- tagcloud


Die Attribute "category" und "tag" bleiben wie gehabt. Sie bestimmen die Filterung nach Kategorien und Schlagwörtern.

Attribut "id" bleibt ebenso. Es können beliebig viele id gesetzt werden. Die Reihenfolge der id wird in der Ausgabe im Classic Editor berücksichtigt.

Ist "id" gesetzt, werden etwaig gesetzte Werte für "category" und "tag" ignoriert, da eine zusätzliche Filterung nach Kategorie und/oder Schlagwort unnötig ist.

Für den Fall, dass eine Reihe an ids ausgegeben werden soll und danach nach Kategorien und Schlagwörter gefilterte FAQ, müssen die Anwender zwei Shortcodes hintereinander nutzen.


Was hältst du davon?


Beispiele:
"Zeige alle FAQ zu "category 1" mit ausgeklappten Accordeons und einem Button und darüber ein Glossar bezogen auf die Schlagwörter als Tagcloud:
[faq category="category_1" layout="tag expanded expand_button tagcloud"]

"Zeige FAQ mit ID 345, 123 und 876 in dieser Reihenfolge ohne Titel und ohne Accordeons an":
[faq id="345, 123, 876" layout="no_title no_accordeon"]

"Zeige alle FAQ mit einem Glossar von A-Z bezogen auf alle Kategorien in beim Laden geschlossenen Accordeons an ohne expand-all-button":
[faq layout="category"]

**Comment by xwolfde** [comment]
Der Enfachheit halber und weil wir voran kommen müssen, würde ich ja sagen.

Aber ich glaub nachhaltig ist es nicht, wenn wir in layout="" Werte mischen, verschiedenerart sind; Also Werte sind aber auch Funktionen sein können. Beispielsweise sind die Fakultätsfarben allesamt Dinge, die auf die Class wirken aber das generelle Aussehen sonst nicht ändern. Während expand_button  und tagcloud Funktionen sind, die die Ausgabe komplett ändern. 
Auch "no_"_Werte könnte man mit  hide="" umsetzen, wie ich es oben vorschlug.

Aber mach es ruhig so, wie du es vorschlugst.

Nur eines ändere bitte:
Lass das mit den Farben weg und ergänze statt dessen das Attribut class="".
Damit wird dann nichts weiter gemacht als, dass dessen Inhalt in dem die jeweiligen Ausgabe umrandende &lt;div&gt; mit einer CSS-Class ergänzt wird:

Also wenn du den Shortcode
[faq class="med irgendeine andere classname"]
hast, wird das umrandende Div dann dazu:

&lt;div class="fau-faq med irgendeine andere classname"&gt;

....

&lt;/div&gt;


(Das wir um jeden SHortcode ein Div drumherum haben wollen mit der Class vom Namen des Plugins war ja auch mal definiert worden

**Comment by thenickless** [comment]
Folgendes werde ich nun zügig umsetzen:


[faq 

glossary="category|tag  a-z|tabs|tagcloud" (default: a-z)

category="cat_1, cat_2, ..."

tag="tag_1, tag_2, ..."

id="321, 123, 456, ..." (bestimmt auch die Reihenfolge der Ausgabe)

hide="accordeon title glossary" 

show="expand-all-link load-open" (Attribute von elements/accordeon)

class="med|nat|phil|rw|tk beliebige-classnamen" (Farbwerte von elements/accordeon + classnames für umrandendes DIV)

sort="id|title"

order="asc|desc"

]



Enthält auch Anforderungen von https://github.com/RRZE-Webteam/rrze-faq/issues/37

**Comment by thenickless** [comment]
umgesetzt in 4.16.0 

siehe https://github.com/RRZE-Webteam/rrze-faq/issues/31#issuecomment-621715308
