### ISSUE TITLE
Meldung "FAQ existiert nicht"

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-faq#33]
Ist:
Wird eine ID im Shortcode verwendet, die nicht gefunden wird, da sie gelöscht wurde - manuell oder über Sync, da diese FAQ im Remote System gelöscht wurde, dann erscheint keine Ausgabe.

Soll:
In diesem Fall eine Meldung ausgeben, damit Redakteur/Admin erkennt, warum keine FAQ ausgegeben werden kann.

**Comment by xwolfde** [comment]
Das interessiert aber den User nicht. Für den wäre das eine Null-Info, die ihn verwirrt.

Wenn, dann via Shortcode-Parameter, welches eine optionale Errormsg. definiert. Ich würde das nicht global festsetzen, da die Errormsg je nach Kategorie und Quelle auch unterschiedlich sein könnte.

ggf so:
[faq category="bla" show="errormsg" errormsg="Text"]

Wenn dies der Fall ist, den text immer im HTML-Markup ausgeben, den wir bei Warnings nutzen:
`
<div class="alert alert-warning" style=""><strong>Hinweis:!&nbsp;</strong>Und der dazugehörige Alert.</div>
`

**Comment by thenickless** [comment]
"Das interessiert aber den User nicht. Für den wäre das eine Null-Info, die ihn verwirrt."

wird darum nicht umgesetzt. 

Es wäre ausschliesslich bei Attribut "id" technisch möglich, da bei "category" oder "tag" nicht bestimmt werden kann, ob bei einem der vorangegangenenen Syncs ein FAQ auf dem Remote-System vorhanden war, das nun nicht mehr vorhanden ist.
