### ISSUE TITLE
glossarystyle per default auf ''

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-faq#34]
Dazu alle bereits vorhandenen Beiträge und Seiten aller Websites mit aktivem RRZE-FAQ durchgehen und anpassen:

- wo aktuell A-Z ausgeben wird, muss glossarystyle="a-z" eingetragen werden
- wo aktuell glossarystyle="" angegeben ist, glossarystyle entfernen

**Comment by xwolfde** [comment]
Nein, bitte abwärtskompatibel bleiben!
Sonst kriegen wir Probleme mit den Leuten, die es so schon einsetzen und erwarten.

Default ist die Ausgabe von A-Z.

**Comment by thenickless** [comment]
> Nein, bitte abwärtskompatibel bleiben!
> Sonst kriegen wir Probleme mit den Leuten, die es so schon einsetzen und erwarten.
> 
> Default ist die Ausgabe von A-Z.

bleibt somit wie umgesetzt
