### ISSUE TITLE
Accordion-Funktionen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#37]
Von DDW kam der Wunsch, dass man das Elements-Accordion (https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/elements/accordion/) steuern kann hinsichtlich der Aufklappen-Funktion.

> Kannst du es (generell oder als Option) einbauen, dass man für die Collapsibles den Button "alle aufklappen" bekommt? Vielleicht mit drei Einstellungsmöglichkeiten:
> - none (Knopf ist nicht da)
> - inactive (Knopf ist vorhanden, aber nicht aktiv)

Accordion hat die Attribute:

title = “ „ | Erzeugt die Überschrift im Accordionbalken | title = „Meine Überschrift“
load= „“ | Das Akkordionfach ist beim Laden der Seite geöffnet | load = „open“
color = “ „ | Färbt den Accordionbalken in eine der folgenden Fakultätsfarben: phil med nat rw tf Wird das Attribut leer gelassen, ist es die Standard-FAU Farbe | color = „philfak“
expand-all-link=““ | Erzeugt einen Button um alle Akkordionfächer auf einmal zu öffnen | expand-all-link=“true“

Ich würde es daher so machen, dass du das über den show="" Parameter udn einen Accordion-Suffix  steuerst:

show="accordion"   - zum EInschalten der Accordion-Funktion mit dessen Defaults

und dann Sub-Parameter

accordion-title=""
accordion-load=""
accordion-color=""
accordion-expand-all-link=""

**Comment by thenickless** [comment]
Siehe https://github.com/RRZE-Webteam/rrze-faq/issues/31#issuecomment-621715308

**Comment by thenickless** [comment]
umgetzt in 4.16.0
