### ISSUE TITLE
Shortcode-Hilfe bei nicht edierbaren gesyncten FAQs

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#39]
Bitte die Shortcode-Hilfe (Metabox) auch bei den FAQs anzeigen, die gesynct wurden und nicht edierbar sind.

![grafik](https://user-images.githubusercontent.com/1070669/79542187-b472a880-807a-11ea-80b4-3053bddfbd65.png)

**Comment by thenickless** [comment]
ist in Version 4.8.4 umgesetzt
