### ISSUE TITLE
Hinweis bei nicht edierbaren FAQs ergänzen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#40]
Bei gesyncten nicht edierbaren FAQs wäre es hilfreich, wenn der Hinweistext, dass nicht bearbeitet werden kann, um ein Link zur Quelle ergänzt wird.

Z.B.:

You can edit the FAQs at the source: $DOMAIN/wp-admin/edit.php?post_type=faq

**Comment by thenickless** [comment]
umgesetzt in 4.9.6 mit Deeplink, um die aufgerufene FAQ auf der Quelle editieren zu können
