### ISSUE TITLE
Accordions

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#6]
Der Accordion-Code soll nicht mehr selbst gebaut werden, sondern auf RRZE Elements beruhen.

Wenn das Plugin RRZE Elements nicht vorhanden ist, soll nur eine simple Basisausgabe erfolgen ohne Accordionfunktionalität.

**Comment by xwolfde** [comment]
D.h. Check einbauen, ob RRZE ELements vorhanden und aktiv ist.
Wenn ja, dann den Accordion-Shortcode von RRZ-Elements bzw- dessen Functions nutzen.

**Comment by thenickless** [comment]
in 4.3.6 umgesetzt
