### ISSUE TITLE
"Auswahl einschränken" funktioniert in der Backend-Übersicht der FAQ einträge nicht korrekt.

### ISSUE THREAD

**Issue by ej64ojyw** [RRZE-Webteam/rrze-faq#73]
Übernommen aus Helpdesk: http://go.fau.de/9p1-j
Wenn in der Übersicht aller FAQ-Artikel im Backend eine Kategorie gewählt wird und der Button "Auswahl einschränken" aktiviert wird, erfolgt keine Ausgabe. Aufgetreten bei der Seite: https://www.rrze.fau.de/ 

![grafik](https://user-images.githubusercontent.com/58593037/99661645-6edcea80-2a64-11eb-9615-d1730630d26a.png)

Ab und zu erfolgt auch die Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/58593037/99661888-c9764680-2a64-11eb-8d8b-0923e4d6e062.png)
Wenn man versucht nach unerfolgreicher einschränkung eine weitere Kategorie zu wählen.

**Comment by thenickless** [comment]
Bug lag an Theme RRZE-2019 und ist mit https://gitlab.rrze.fau.de/rrze-webteam/rrze-2019/-/commit/a202ca749d8a120c64264e0a1dbea16c09b75149 gefixt.
