### ISSUE TITLE
Das Feld "Sortierung" bei einer FAQ hat keinen Einfluss.

### ISSUE THREAD

**Issue by faurex** [RRZE-Webteam/rrze-faq#78]
Mit folgenden Shortcode habe ich die FAQ eingebunden:

[faq category="praktikumsamt" hide="glossary" show="expand-all-link" class="tk"]

In einer einzelnen FAQ "Wie lange dauert die Anerkennung des Praktikums durch das Praktikumsamt?" dieser Kategorie habe ich in Sortierung den Wert 100 eingetragen, siehe Screenshot. 

![image](https://user-images.githubusercontent.com/44059562/108983739-74635580-768f-11eb-9db9-b81387e241c5.png)

In der Ausgabe hat dieser Wert bei "Wie lange dauert die Anerkennung des Praktikums durch das Praktikumsamt?" keinen Einfluss, siehe Screenshot.

![image](https://user-images.githubusercontent.com/44059562/108983873-9e1c7c80-768f-11eb-9e4f-fba33a7d50f3.png)

Die anderen FAQs haben keinen Wert, auch keine 0.

**Comment by thenickless** [comment]
Der Parameter "sort" muss angeben werden, wenn nicht nach Titel sortiert werden soll.

In diesem Fall
[faq category="praktikumsamt" hide="glossary" show="expand-all-link" class="tk" sort="sortfield"]

Anleitung: https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/rrze-faq/attribute/sort/

Einschränkung ist derzeit, dass die Einträge ohne Wert zuerst gelistet sind, dann die mit einem Wert für "Sortierung".
