### ISSUE TITLE
Lokale Galerie teilweise fehlerhaft

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#8]
Die lokale Galerie wird ebenfalls nur fehlerhaft angezeigt innerhalb eines Accordions

**Comment by xwolfde** [comment]
Anmerkung: In der Endpoint-Ansicht ist die Galerie vorhanden.

**Comment by thenickless** [comment]
4.3.6 liefert diesen Fehler nicht
