### ISSUE TITLE
Mailto-Links von externen FAQs werden falsch gesetzt

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#84]
Beispiel:
Der FAQ-Eintrag https://www.anleitungen.rrze.fau.de/faq/welche-hardware-wird-zur-durchfuehrung-von-zoom-meetings-benoetigt/
enthält ein mailto:Link (letzter Link am Ende).

Bei einem Embedding des FAQs in einer anderen Website wird daraus:

`<a href="https://www.anleitungen.rrze.fau.de/mailto:rrze-hardware@fau.de" ..>`

**Comment by thenickless** [comment]
Den Bug kann ich nicht nachvollziehen. Mit Shortcode z.B. [faq id="123"] gibt es keinen Fehler. Beim Embedding des URLs wird der Titel ausgeben. Wie hast du den FAQ-Eintrag embedded?

**Comment by xwolfde** [comment]
Hier kannst du es sehen:
https://www.beta.wordpress.rrze.fau.de/plugins/rrze-faq/beispiele/glossar-mit-kategorien-als-a-z-register/#innerID-2218428
