### ISSUE TITLE
Links auf Tabs in derselben Seite funktionieren nicht

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#87]
Beispiel:
https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/rrze-faq/beispiele/glossar-mit-expliziten-schlagwoertern-als-tabs/

Klick oben auf einen der 3 Links. Es geschieht nichts, die Accordions darunter öffnen sich nicht.

**Comment by thenickless** [comment]
Das ist eigenartig.

"Mit Rechtsklick in neuem Fenster öffnen" funktioniert. Auch auf dem DEV und den LIVE-Instanzen funktioniert es.
Auffällig ist, dass auch das Beispiel 

[https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/elements/accordion/accordion-sprungmarken/](https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/elements/accordion/accordion-sprungmarken/)
 sich genauso verhält. Auf Klick öffnet sich das Accordion nicht, aber in einer neuen Seite schon.

**Comment by thenickless** [comment]
Liegt an Bug in RRZE-Elements https://github.com/RRZE-Webteam/rrze-elements/issues/131

**Comment by thenickless** [comment]
ist gefixt
