### ISSUE TITLE
Endpoints nicht korrekt umgesetzt

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#9]
Die Archiv/Index-Anzeige der FAQ-EInträge ist nicht korrekt umgesetzt.
Zudem sollte als Endpoint /faq/  registriert sein stat /glossary/ .

Der Endpoint für einzelne Eintrage zeigt einrichtiges Ergebnis an, zeigt allerdings auf /glossary/$faq-slug

**Comment by xwolfde** [comment]
Zudem sollte auch die Kategorie unterstützt werden.

FAQ-Einträge (Index) mit Kategorien sollten hierarchisch abrufbar sein.

Beispiel:
  -+  KategorieOben
    +--      KategorieUnten
  
Sollten auch so erreichbar sein:

  /faq/KategorieOben/KategorieUnten/


Da ein FAQ-EIntrag aber auch mehreren Kategorien gleichzeitig angehören kann und auch der Oberkategorie zugeordnet sein kann, sollte er in dem Fall natürlich auch im Index darüber sichtbar sein.
Also in 
 /faq/KategorieOben/

**Comment by thenickless** [comment]
"Die Archiv/Index-Anzeige der FAQ-EInträge ist nicht korrekt umgesetzt.
Zudem sollte als Endpoint /faq/ registriert sein stat /glossary/ .

Der Endpoint für einzelne Eintrage zeigt einrichtiges Ergebnis an, zeigt allerdings auf /glossary/$faq-slug"

ist umgesetzt in 4.3.6


Zu "/faq/KategorieOben/KategorieUnten/" besteht noch Klärungsbedarf, da Kategorien können beliebig verschachtelt werden können: child->parent->grandparent->greatgrandparent->...

Aktuell sind diese Endpoints umgesetzt:
- faq
- faq_category
- faq_tag
sowie Filter darauf.

Zu klären ist, ob darüberhinaus noch Bedarf besteht, https://github.com/RRZE-Webteam/rrze-faq/issues/9#issuecomment-611419830 umzusetzen.

**Comment by xwolfde** [comment]
Ok. 
Ob die Abbildung der Hierarchie wirklich notwendig ist, würde ich dann noch abwarten. Stellen wir das also erstmal zurück.
