### ISSUE TITLE
Darstellung ohne Accordion

### ISSUE THREAD

**Issue by cassandre** [RRZE-Webteam/rrze-faq#92]
... nur mit Überschrift und Text.

Dabei wäre noch der Sportcode-Parameter `hstart=""` wichtig, mit dem man die Überschriftenebene (1-6) einstellen kann.

(vgl. https://github.com/RRZE-Webteam/rrze-glossary/issues/21)

**Comment by thenickless** [comment]
mit 4.27.15 umgesetzt. 

Darstellung ohne Accordeon war bereits umgesetzt (siehe "hide" https://www.wordpress.rrze.fau.de/plugins/fau-und-rrze-plugins/rrze-faq/attribute/ ) - hinzugekommen ist der Shortcode-Parameter "hstart" (default: 2)

**Comment by cassandre** [comment]
OK, da hätte ich nicht gesucht. Bitte noch hide="accordion" einbauen – accordeon gibt es nicht (nur deutsch Akkordeon oder englisch accordion), kann man aber aus Abwärtskompatibilitätsgründen drin lassen.
