### ISSUE TITLE
hstart wirkt nicht?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-faq#99]
Folgender Shortcode ist im EInsatz:

[faq category="schriften" hide="glossary" hstart="3"]

Trotzdem werden die Accordions mit h2 aufgebaut.

**Comment by thenickless** [comment]
gefixt

( ist mir leider entgangen, dass hstart nun auch bei Accordions verwendet werden kann - gibbet seit https://github.com/RRZE-Webteam/rrze-elements/pull/141 - bislang hatte rrze-faq hstart nur bei allen Ausgaben ohne  "Accordions generated by rrze-elements" genutzt, jetzt überall :-)
